# Generated by Django 2.1 on 2018-09-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='number_of_token',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
