# Generated by Django 2.1 on 2018-09-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180904_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='number_of_token',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='sms_verify_token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
