# Generated by Django 2.1 on 2018-09-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180911_1125'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='whitepaper',
            table='white_papers',
        ),
    ]
