# Generated by Django 2.1 on 2018-09-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180911_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhitePaper',
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={},
        ),
    ]
