# Generated by Django 2.1 on 2018-10-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('main', '0009_whitepaper_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPagesModel',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
            ],
            options={
                'verbose_name_plural': 'CMS',
            },
            bases=('flatpages.flatpage',),
        ),
        migrations.AlterModelOptions(
            name='kyc',
            options={'verbose_name_plural': 'Manage KYC'},
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': "User's Detail"},
        ),
        migrations.AlterModelOptions(
            name='whitepaper',
            options={'verbose_name': 'WhitePaper', 'verbose_name_plural': 'White Papers'},
        ),
    ]
